### ISSUE TITLE
Ligatury se nepřejmenují, aplikace spadne

### ISSUE THREAD

**Issue by designiq** [lexislav/CleaningScripts-for-GL2.3#1]
Lexo, pokus přejmenovat ligatury mi končí pádem aplikace. Skript mám stažený ve složce skripty, vedle leží ten json. Označím-li několik ligatur a spustím-li skript, spadne to. Zkouším to na tom fontu Pozorius TEST.

**Comment by lexislav** [comment]
Hmm, myslíš “Add sufixes to ligatures”?
Asi mi prosím pošli tvůj aktuální json… Dost možná v něm je nějaká chybka.
A script na to nedával do teď pozor. Což teď opravuji…
V tom případě ti vypíše JSON error nebo něco takového a funkce, které na něm závisí se přeskočí.
L*

**Comment by designiq** [comment]
JSON jsem neměnil, je to ten tvůj originální. Resp. automaticky klonovaný z
GitHubu.
Filip

Dne 7. června 2016 11:11 lexislav notifications@github.com napsal(a):

> Hmm, myslíš “Add sufixes to ligatures”?
> Asi mi prosím pošli tvůj aktuální json… Dost možná v něm je nějaká chybka.
> A script na to nedával do teď pozor. Což teď opravuji…
> V tom případě ti vypíše JSON error nebo něco takového a funkce, které na
> něm závisí se přeskočí.
> L*
> 
> > 1. 6. 2016 v 10:01, designiq notifications@github.com:
> > 
> > Lexo, pokus přejmenovat ligatury mi končí pádem aplikace. Skript mám
> > stažený ve složce skripty, vedle leží ten json. Označím-li několik ligatur
> > a spustím-li skript, spadne to. Zkouším to na tom fontu Pozorius TEST.
> > 
> > —
> > You are receiving this because you are subscribed to this thread.
> > Reply to this email directly, view it on GitHub <
> > https://github.com/lexislav/CleaningScripts-for-GL2.3/issues/1>, or mute
> > the thread <
> > https://github.com/notifications/unsubscribe/AG0PVSUYo5GoXjHB8Fq9oZjg2jPReAEUks5qJSVdgaJpZM4IvqKo
> > .
> 
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub
> https://github.com/lexislav/CleaningScripts-for-GL2.3/issues/1#issuecomment-224223795,
> or mute the thread
> https://github.com/notifications/unsubscribe/AFxWHR1NTPZ5PDzdLiizSrUHXZes4Dwwks5qJTXMgaJpZM4IvqKo
> .

## 

Filip Blažek / Designiq – studio grafického designu
Letenské nám. 3, 170 00 Praha 7 / T 272049104
www.designiq.cz

**Comment by lexislav** [comment]
aktuální verze by neměla shodit aplikaci (už tam je kontrola jestli je json ok), ale stejně mi ho raději pošli.
jinak je asi dobré použít nějaký json validátor https://www.google.cz/search?client=safari&rls=en&q=json+validator&ie=UTF-8&oe=UTF-8&gfe_rd=cr&ei=aJlWV_OJI-ik8we3uKTgCg.
Ikdyž do předpřipravených zívorek lze samozřejmě vložit python list. Přidávání dalších ligatur apod. ale může působit zmatek v chluaptých závorkách :-/
L*

**Comment by lexislav** [comment]
A přejmenovaný na pozorius TEST… atd?
Zajímavé.
Každopádně teď by to snad padat nemělo, mělo by to vypsat WARNING…
L*

**Comment by designiq** [comment]
Ok, vyzkouším, až budu online.
Teď jsem na mobilu jen.
Díky!
F.
Dne 7. 6. 2016 11:54 napsal uživatel "lexislav" notifications@github.com:

**Comment by lexislav** [comment]
tyhle dva se nám nějak promíchaly…
