### ISSUE TITLE
Chybějící funkce "Apply to all glyphs"

### ISSUE THREAD

**Issue by designiq** [lexislav/CleaningScripts-for-GL2.3#2]
Lexo, pod volbu fontů (aktuální/všechny) bych prosím přidal ještě zaškrtávátko "Apply to all glyphs", které by podobně jako volby nahoře rovnou vybralo všechny glyfy. Defaultně bych ho nechal zapnutý.
Díky.

**Comment by lexislav** [comment]
Aha, no defaultně to projíždí všechny glyphy. S projížděním výběru jsem zatím nepočítal.
Jinak řečeno bys chtěl, aby to umělo projíždět také pouze aktuální výběr glyphů, chápu to dobře?
To si nejsem jist, jestli u některých voleb nebude drobet problém - speciálně u hledání duplikátů… například co když vybraný znak má duplikát, který není v aktuálním výběru?
Nebo že by se to vztahovalo pouze na některé funkce skriptu? Např. na update glyph info, ale naopak na hledání duplikátů třeba nikoliv?
L*

**Comment by designiq** [comment]
S těmi ligaturami to zlobí.

Hlásí mi to -- Adding suffixes to ligatures skipped for missing or
corrupted json config file

Co mám špatně?

Mně by asi stačilo, kdyby ten skript fungoval
– automaticky na všechny glyfy ve fontu
– automaticky na všechny glyfy v otevřených fontech

Vybrané znaky vlastně nepotřebuju.

Pak mám pocit, že Glyphs mají nějaký trik, který skript zásadně zrychlí,
kdysi jsme řešili něco podobného, programátor poslal skript na
support@glyphsapp a tam pomohli. Něco udělali jinak a skript byl najednou
100x rychlejší. Zkusím to najít v mailu.

Filip

Dne 7. června 2016 12:34 lexislav notifications@github.com napsal(a):

> Aha, no defaultně to projíždí všechny glyphy. S projížděním výběru jsem
> zatím nepočítal.
> Jinak řečeno bys chtěl, aby to umělo projíždět také pouze aktuální výběr
> glyphů, chápu to dobře?
> To si nejsem jist, jestli u některých voleb nebude drobet problém -
> speciálně u hledání duplikátů… například co když vybraný znak má duplikát,
> který není v aktuálním výběru?
> Nebo že by se to vztahovalo pouze na některé funkce skriptu? Např. na
> update glyph info, ale naopak na hledání duplikátů třeba nikoliv?
> L*
> 
> > 1. 6. 2016 v 10:02, designiq notifications@github.com:
> > 
> > Lexo, pod volbu fontů (aktuální/všechny) bych prosím přidal ještě
> > zaškrtávátko "Apply to all glyphs", které by podobně jako volby nahoře
> > rovnou vybralo všechny glyfy. Defaultně bych ho nechal zapnutý.
> > Díky.
> > 
> > —
> > You are receiving this because you are subscribed to this thread.
> > Reply to this email directly, view it on GitHub <
> > https://github.com/lexislav/CleaningScripts-for-GL2.3/issues/2>, or mute
> > the thread <
> > https://github.com/notifications/unsubscribe/AG0PVQmxMaq16ZEChxdlZxsoDVRDOzshks5qJSWfgaJpZM4IvqN4
> > .
> 
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub
> https://github.com/lexislav/CleaningScripts-for-GL2.3/issues/2#issuecomment-224242434,
> or mute the thread
> https://github.com/notifications/unsubscribe/AFxWHV5jteQq3M5CHRdBs0lSOt5IJrhkks5qJUkigaJpZM4IvqN4
> .

## 

Filip Blažek / Designiq – studio grafického designu
Letenské nám. 3, 170 00 Praha 7 / T 272049104
www.designiq.cz

**Comment by lexislav** [comment]
Fakt nevím. Budu na to muset mrknout u tebe, proovnat verze atd.
Mě to napíše s tím základním jsonem toto:

==== Starting ====
NOTE: Only current font will be processed

# Proccesing font: Pozorius 2s (contains 1016 glyphs)

---

-- font has json file attached and file seems OK.

-- Adding suffixes to ligatures
-- Defined suffixes added to 3 glyphs.

===== Done. =====

Přikládám pro jistotu oboje potřebné emailem, jestli není chyba v nějakém git vezování.
L*

**Comment by lexislav** [comment]
Jen ještě pro jistotu:
json musí být ve složce, kde je font a musí se jmenovat stejně jako font, krom koncovky. Ta bude json.

**Comment by designiq** [comment]
Aha, a nešlo by jako Fall Back vzít soubor json vedle skriptu, pokud není
vedle fontu? To by bylo ideální. Jinak díky.
F
Dne 7. 6. 2016 20:18 napsal uživatel "lexislav" notifications@github.com:

**Comment by lexislav** [comment]
To by samozřejmě šlo. Beru to tak, že to funguje, mlžeme uzavřít, akorát je tu request na další feature :-)
